travis:
  secure:
    BINSTAR_TOKEN: pLZwSUq8COGhJ4/+vjDfsPpS8AqWvZPbdV86bBOtErzZmGIkSSD+XlbCgPd1w6ul7/Dsqm0TZBxfHVq+GqEASvWf1v5psauUuSG6mcE75826R9vjviNqHv+MlHUCspzbZnkGaXhvZ9KWud9bEynWzw5OYhnN169mrI2k2T1XN5cJehYmPUml8MwQflP6UIXai4uMTzM5kDnPKkeJt2W3VK4qQKuqvFkfo9z9tKIGFfXCfikOPUiAp1nqWsUgnvIJi07yMTz3dNRIxC7qMQlgSpGwjQCDzLhgI+PHmE9d7R4+DZMQRW00fXUX2PsPu53E+UOdYh6mwr8IeGJP3YC6/tTzynzEtPftQzIH9vuFkwp6fiD/yl2r/NaNAsOXEJcm548qaCjfQVaxJeIJxmcLg0wZqGKg6d+j4V5AXK9QvbHFfYgMIr7526V3w/C1YgNiW9eSga1BLc3ssJxGFYSu8spK7Psivi2oyOWBD/m5OCYopsZSnpvKENIbIUTWVdoGMiA09+x17aXM+K5X+PMvMi8Omhr0SCKL8lLJKu8xwv+dDYAv6vKO0JuIz12/WdJvncxLRKoJUxB6iS/Lxs4tWglgR4jQqDBtw9tVyaFGsyash0NpuPO2py81WyquY1Jr3rdSRlipXm7eD/vgqZ+Pw2Uq7RF+cgb7MZaFjRV3GjE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
