travis:
  secure:
    BINSTAR_TOKEN: agRRGp5FmKOFchEI4IIVIAeroScJEAtgp9JLTZOBlLaW1k1d/Cz8oa7iXzC3yu3PWUdfO0laODo3mMz7qGa5ItdqfN/kx8Hqf2D+44P7j0uzrKfEeOyn3NqFg9mEgU5IJ61n7E6rRQZOiX/nOMKiYUHoQmPm+s2U8th5DMCkTO+orLVjBmwwCgkkxQRLM8cGlh3/na8XWRY6N5Pzuh36pRMUDvRSDFJTGtT3po2IlBTTu8pQC2KD2YkDjHOKiII+9B7u55KS0JHRQ1ghPwOXP4jvQRfJ8dFypxPl2BF2B9+GwzXbPNcdenzMqdIPIQhNmg90TUoPigXuxpBeL2wMafEDyiPOtuBZ/EFwg1O/xm9SKOBTPZf51x3Br1cJGRj2jnfUfELc0SvHecJtLc3i26C5MeG3ddsH5kAyXD3JteNvVXDWXpaJXAfOtj1tocwvN5gk9+neNw4Lbxa4JGZQ+VwrwC4ADEuwFC/iY+ydnyiMd202Z/ACjqSmENK3q3uXGUU/Fb6rFHF+S245OuzWmwX2wJUY19Tflsr6xWGGw1kH2EY1J1eeksKt3EwBgs0dyeIKy3RE207WA3mQjGcw/tNMTg332cJvK3IuAbkNsCxOe4OZz4Ft7Pp9zGrT3vkHsNCf1e/19c5H3XSt+b+G9zi5i9AhqSz9uV4gDxsaOkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
