travis:
  secure:
    BINSTAR_TOKEN: kxGzWLotDJ8+kbZvKFGNECYZpbEMpgi0m/djIThCPFOjQXEkt/Qe1qME/VzGxI+/S3b9Hgs/b3o87iowNAum/jJ4Macz4RkcjKS/+w3NDi5mr1nIy/b4cOPYexKNYmZo0x1V1ak6o3Gn6m6a2Bq9kJz1SnFpZpNs3AA6oPazrzKuD5fdF2OGo0hYTrBLV4Af8iu9MuLLayw2uYx/TzP7TqDLrPBwCFRV53BHHNnCJRnvBAluls5ylqzpFiqFuY9cMkIKMQUTknLPn5Zypaw72NDhSuVmO/aqWOBH+ikB5K8SN90m56ih1sQ1eaYskiV/aui+E8qrh5wm7OCdfw+xPg8sv4ar+MNX1fOJnVPbIRWtn+Qtrh20Wj0/GD3hxOMJZ38fBWWSsZvjlw0mShCkg1sc1tInfA3PMV24262GoNw9cKNKEBhXBKD9Y3tfVZ5MVMac35W8EcdYq/7fHGA9UH2jNv13EUkafTI9TWrs/fDEL/e8vNtd6goTz5duuOoYGsvEl7kbf6V6Qs0+qJ9p2z6mG6SumvMPZ40nZbXnJaNaDYJibpQ1o7L6CwCjhDSID65agkQtx+4YDx0d23d/5Ti7JtA4UbY1WYsHCI1mwmv9M+EnMWVZw6LiUAYVUJVDbnVtBxjuIVem19cSB3iGHin62wRHq6Eer35uqr7g4tE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
